// export const OPEN_VIDEO_MODAL = 'OPEN_VIDEO_MODAL'
export const CONTACT_FORM_SUCCESS = 'CONTACT_FORM_SUCCESS'
export const CONTACT_FORM_ERROR = 'CONTACT_FORM_ERROR'
export const CONTACT_FORM_PENDING = 'CONTACT_FORM_PENDING'
